OnlineFoodHub/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineFoodHub.Data;

namespace OnlineFoodHub.Controllers
{
    public class DashboardController : BaseController
    {
        public DashboardController(ApplicationDbContext context)
         : base(context) { }

        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineFoodHub/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineFoodHub.Data;
using OnlineFoodHub.Models;

namespace OnlineFoodHub.Controllers
{
    public class PedidosController : BaseController
    {
        public PedidosController(ApplicationDbContext context)
          : base(context) { }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pedidos.Include(p => p.Usuario);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Usuario)
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "UsuarioId", "Contrasenia");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoId,UsuarioId,Fecha,Estado,DireccionIdSeleccionada,Total")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "UsuarioId", "Contrasenia", pedido.UsuarioId);
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "UsuarioId", "Contrasenia", pedido.UsuarioId);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoId,UsuarioId,Fecha,Estado,DireccionIdSeleccionada,Total")] Pedido pedido)
        {
            if (id != pedido.PedidoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "UsuarioId", "Contrasenia", pedido.UsuarioId);
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Usuario)
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido != null)
            {
                _context.Pedidos.Remove(pedido);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedidos.Any(e => e.PedidoId == id);
        }
    }
}

OnlineFoodHub/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineFoodHub.Data;
using OnlineFoodHub.Models;

namespace OnlineFoodHub.Controllers
{
    public class RolesController : BaseController
    {
        public RolesController(ApplicationDbContext context)
            : base(context) { }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rol = await _context.Roles
                .FirstOrDefaultAsync(m => m.RolId == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RolId,Nombre")] Rol rol)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rol);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rol);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rol = await _context.Roles.FindAsync(id);
            if (rol == null)
            {
                return NotFound();
            }
            return View(rol);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RolId,Nombre")] Rol rol)
        {
            if (id != rol.RolId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rol);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RolExists(rol.RolId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rol);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rol = await _context.Roles
                .FirstOrDefaultAsync(m => m.RolId == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rol = await _context.Roles.FindAsync(id);
            if (rol != null)
            {
                _context.Roles.Remove(rol);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RolExists(int id)
        {
            return _context.Roles.Any(e => e.RolId == id);
        }
    }
}

OnlineFoodHub/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineFoodHub.Data;
using OnlineFoodHub.Models;

namespace OnlineFoodHub.Controllers
{
    public class UsuariosController : BaseController
    {
        public UsuariosController(ApplicationDbContext context)
        : base(context) { }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Usuarios.Include(u => u.Rol);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.Rol)
                .FirstOrDefaultAsync(m => m.UsuarioId == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            ViewData["RolID"] = new SelectList(_context.Roles, "RolId", "Nombre");
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UsuarioId,Nombres,Telefono,NombreUsuario,Contrasenia,Correo,Direccion,RolID")] Usuario usuario)
        {
            var rol = await _context.Roles
                .Where(d => d.RolId == usuario.RolID)
                .FirstOrDefaultAsync();


            if (rol != null)
            {
                usuario.Rol = rol;

                usuario.Direcciones = new List<Direccion>
                {
                    new Direccion
                    {
                        Address = usuario.Direccion,
                    }
                };

                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RolID"] = new SelectList(_context.Roles, "RolId", "Nombre", usuario.RolID);
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            ViewData["RolID"] = new SelectList(_context.Roles, "RolId", "Nombre", usuario.RolID);
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UsuarioId,Nombres,Telefono,NombreUsuario,Contrasenia,Correo,Direccion,RolID")] Usuario usuario)
        {
            if (id != usuario.UsuarioId)
            {
                return NotFound();
            }

            var rol = await _context.Roles
               .Where(d => d.RolId == usuario.RolID)
               .FirstOrDefaultAsync();

            if (rol != null)
            {
                var existingUser = await _context.Usuarios
                    .Include(u => u.Direcciones)
                    .FirstOrDefaultAsync(u => u.UsuarioId == id);

                if (existingUser != null)
                {
                    // Actualizar datos principales del usuario
                    existingUser.Rol = rol;
                    existingUser.RolID = usuario.RolID;
                    existingUser.Nombres = usuario.Nombres;
                    existingUser.Telefono = usuario.Telefono;
                    existingUser.NombreUsuario = usuario.NombreUsuario;
                    existingUser.Correo = usuario.Correo;

                    // Manejar la dirección principal
                    if (existingUser.Direcciones.Any())
                    {
                        var direccion = existingUser.Direcciones.First();
                        direccion.Address = usuario.Direccion;
                    }
                    else
                    {
                        existingUser.Direcciones = new List<Direccion>
                {
                    new Direccion
                    {
                        Address = usuario.Direccion,
                        UsuarioId = existingUser.UsuarioId
                    }
                };
                    }

                    // Sincronizar propiedad `Direccion`
                    existingUser.Direccion = usuario.Direccion;

                    // Manejar la contraseña
                    if (!string.IsNullOrWhiteSpace(usuario.Contrasenia))
                    {
                        existingUser.Contrasenia = usuario.Contrasenia;
                    }

                    try
                    {
                        _context.Update(existingUser);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!UsuarioExists(usuario.UsuarioId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }

            ViewData["RolID"] = new SelectList(_context.Roles, "RolId", "Nombre", usuario.RolID);
            return View(usuario);
        }



        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.Rol)
                .FirstOrDefaultAsync(m => m.UsuarioId == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }


        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuarios.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.UsuarioId == id);
        }
    }

}

OnlineFoodHub/Views/Dashboard/Index.cshtml
<div class="container mt-5">
    <div class="text-center mb-5">
        <h1 class="text-primary"><i class="fas fa-chart-line"></i> Bienvenido al Dashboard</h1>
        <p class="fs-5 text-muted">Administra las diferentes secciones de la aplicación desde aquí:</p>
    </div>

    <div class="row">
        <!-- Tarjetas de acceso rápido -->
        <div class="col-md-4 mb-4">
            <a href="@Url.Action("Index", "Usuarios")" class="text-decoration-none">
                <div class="card shadow-sm border-primary">
                    <div class="card-body text-center">
                        <i class="fas fa-users fa-3x text-primary mb-3" aria-label="Usuarios"></i>
                        <h5 class="card-title text-dark">Usuarios</h5>
                        <p class="card-text text-muted">Gestiona los usuarios registrados.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="@Url.Action("Index", "Roles")" class="text-decoration-none">
                <div class="card shadow-sm border-success">
                    <div class="card-body text-center">
                        <i class="fas fa-user-cog fa-3x text-success mb-3" aria-label="Roles"></i>
                        <h5 class="card-title text-dark">Roles</h5>
                        <p class="card-text text-muted">Gestiona los roles de los usuarios.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="@Url.Action("Index", "Productos")" class="text-decoration-none">
                <div class="card shadow-sm border-warning">
                    <div class="card-body text-center">
                        <i class="fas fa-box-open fa-3x text-warning mb-3" aria-label="Productos"></i>
                        <h5 class="card-title text-dark">Productos</h5>
                        <p class="card-text text-muted">Gestiona los productos disponibles.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="@Url.Action("Index", "Pedidos")" class="text-decoration-none">
                <div class="card shadow-sm border-danger">
                    <div class="card-body text-center">
                        <i class="fas fa-cart-arrow-down fa-3x text-danger mb-3" aria-label="Pedidos"></i>
                        <h5 class="card-title text-dark">Pedidos</h5>
                        <p class="card-text text-muted">Administra los pedidos realizados.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="@Url.Action("Index", "Direcciones")" class="text-decoration-none">
                <div class="card shadow-sm border-info">
                    <div class="card-body text-center">
                        <i class="fas fa-map-marked-alt fa-3x text-info mb-3" aria-label="Direcciones"></i>
                        <h5 class="card-title text-dark">Direcciones</h5>
                        <p class="card-text text-muted">Gestiona las direcciones de envío.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="@Url.Action("Index", "DetallesPedidos")" class="text-decoration-none">
                <div class="card shadow-sm border-secondary">
                    <div class="card-body text-center">
                        <i class="fas fa-clipboard-list fa-3x text-secondary mb-3" aria-label="Detalles de Pedidos"></i>
                        <h5 class="card-title text-dark">Detalles de Pedidos</h5>
                        <p class="card-text text-muted">Administra los detalles de los pedidos.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="@Url.Action("Index", "Categorias")" class="text-decoration-none">
                <div class="card shadow-sm border-dark">
                    <div class="card-body text-center">
                        <i class="fas fa-tags fa-3x text-dark mb-3" aria-label="Categorías"></i>
                        <h5 class="card-title text-dark">Categorías</h5>
                        <p class="card-text text-muted">Gestiona las categorías de los productos.</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>